### ISSUE TITLE
Not measuring engagement time

### ISSUE THREAD

**Issue by stullesha** [jahilldev/minimal-analytics#15]
I created a new GA4 instance but the CDN code is not recording the average engagement time anymore. https://prnt.sc/mckg9ky5d20j

Edit: I compared my previous GA4 instance and I found there is a greater discrepancy in engagement time between the two instances with regards to average engagement time. The previous one (which I used with the early versions of GA4 code you made) shows everything as I would expect (e.g reading time of 3 minutes), but the latest code has lots of erratic instances like 00 seconds or at most 9 seconds for similar posts.

**Comment by jahilldev** [comment]
Hi there @stullesha,

Thanks for reaching out 👍 

This is a known issue and has been fixed in v1.5.1. Versions >=1.4.6 & < 1.5.0 introduced a better minification strategy to reduce built file size, but unfortunately introduced a mangled query parameter (`_et`) which caused engagement time to be lost.

Updating to >=1.5.0 will fix this, although I suggest updating the latest version.

**Comment by stullesha** [comment]
Thank for clarifying. I thought there might have been an issue hence the report. Perhaps you might keep two copies of minified and unminified version, since someone like me, who uses an SSG with [inbuilt minification](https://github.com/tdewolff/minify), will be doing it twice.

**Comment by jahilldev** [comment]
No problem 👍 

If you're using a build tool that imports the module then this won't add any additional overhead to the process, and will likely be skipped as it resides in your `node_modules` folder. 

If you're using a CDN then this won't be applicable anyway.

**Comment by stullesha** [comment]
Hugo has a superb `resources.GetRemote ` feature that fetches the CDN code automatically during build time (e.g locally, on Cloudflare Pages/Netlify, etc.). So it is a "set and forget" option that always fetches the latest code. However, I have enabled minifcation since the code is combined with the tracking code that I pasted in a local file, so I am not sure if the minified code is minified again or skipped.

**Comment by jahilldev** [comment]
That sounds interesting, I've only very briefly dabbled with Hugo and it's features.

I wouldn't worry to much about it, even if it is minified again, the overhead of this on your build time will be less than negligible, and won't cause any harm.

I'm going to close this issue for now, please feedback if needed 👍

**Comment by stullesha** [comment]
Alright. Thanks. I am a beginner with Hugo, so also, not really deep into its features yet. This code was also shared in a Hugo forum on discourse, so I am sure some of your recent followers/ users came from there as well.

**Comment by jahilldev** [comment]
Great, thanks for the input.

Let me know how it goes 👌
