### ISSUE TITLE
Tracking code

### ISSUE THREAD

**Issue by stullesha** [jahilldev/minimal-analytics#16]
Your example is `GX-XXXXX` but in my GA4 property it is `G-XXXXX`.

**Comment by jahilldev** [comment]
This is only meant as an example / guide. If this is proving confusing for yourself and others I'll remove the superfluous X.

Thanks 👍

**Comment by stullesha** [comment]
> f this is proving confusing for yourself

It does, but coz I am new to ga4.

**Comment by jahilldev** [comment]
@stullesha Done!

Thanks for the suggestion 👍

**Comment by stullesha** [comment]
Thanks.
