### ISSUE TITLE
Add a note about what options to toggle in GA4

### ISSUE THREAD

**Issue by stullesha** [jahilldev/minimal-analytics#18]
Hi. While this might seem obvious to others, could you kindly add a note in the readme file about what options users need to toggle in their GA4 property? (I think pageview, scroll and search?). Perhaps as a new paragraph just before or after the "Getting Started" heading.

**Comment by jahilldev** [comment]
Hi @stullesha,

By default, the official GA4 script tracks `page_view`, `user_engagement`, `scroll` and `click` events "out of the box". No additional config is required in the UI, or elsewhere.

This minimal version is exactly the same, e.g it "Just Works".

I've actually just added `click` event tracking in v1.6.0, so you'll now get those events too, bringing it to default feature parity with the official script.

If I've missed something, or I haven't answered your question, please let me know.

Thanks

**Comment by stullesha** [comment]
I am actually referring to the ''Enhanced measurement" section of GA4.

**Comment by stullesha** [comment]
I think you are misunderstanding my question. If a user doesn't toggle search and scroll in the ga4 property, will your code still track those features? This is what I am referring to!

**Comment by jahilldev** [comment]
> If a user doesn't toggle search and scroll in the ga4 property, will your code still track those features?
@stullesha Oh right, I see, yeh your question wasn't super clear, you probably should have lead with in the first place!

So, of the default events that GA4 _can_ track, this package only supports the first four:

![Screenshot 2022-06-10 at 20 11 34](https://user-images.githubusercontent.com/13650046/173134596-4f012877-1d8b-4fe8-8ed6-6591fc695b94.png)
- Page View
- Scrolls
- Outbound Links
- Site Search

This is kind of briefly mentioned in the opening paragraph, but I see your point, it could be clearer 👍 

But to answer your *actual* question: 

**If a user turns off, or does not turn on, one of the supported tracking event types, does it still track those events?**
Yes, these will still be tracked. The reason being, we are not requesting or receiving any GA4 UI defined config here, we're merely sending data to an endpoint. The flow of data is one way. 

If you want to have more fine grained control over the GA4 tracking events, it's advised you use the official library. Implementing the complete suite of features of GA4 is, as I say, out of scope unfortunately, for this particular package.

I hope that better answers your question!

**Comment by stullesha** [comment]
Alright! Now you have answered my question.

**Comment by stullesha** [comment]
Okay. Which event name is for outbound links?

**Comment by jahilldev** [comment]
@stullesha  It will show up in your GA4 reports as `click`:
![Screenshot 2022-06-10 at 21 38 35](https://user-images.githubusercontent.com/13650046/173146782-a9efe7ba-9c97-42df-aee9-c56c1d8bf4d1.png)

You can see relevant event params tracked as part of that event by clicking on it. I'd suggest looking up the official docs on how to generate reports on these. 

Also remember there's some lag between events being tracked, and showing up in your reports.

**Comment by stullesha** [comment]
Thank you. I will keep that in mind.

**Comment by stullesha** [comment]
I can confirm the click event is now live.
