### ISSUE TITLE
Adding to Hugo

### ISSUE THREAD

**Issue by rbn30117** [jahilldev/minimal-analytics#19]
Someone has [done a tutorial](https://discourse.gohugo.io/t/add-minimal-analytics-google-analytics-v4-to-hugo/39016).

**Comment by jahilldev** [comment]
@stullesha This is fantastic, great contribution 👌

**Comment by stullesha** [comment]
> or perhaps an `INTEGRATION.md` document

This would be perfect.

**Comment by jahilldev** [comment]
Hey @rbn30117,

I'm going to close this issue for now, feel free to contribute to an integration doc if you have time 👍 

Thanks
