### ISSUE TITLE
Using jsDelivr?

### ISSUE THREAD

**Issue by stullesha** [jahilldev/minimal-analytics#21]
Using the Hugo method I told you about which imports the CDN file automatically during build, sometimes the build fails due to timeout when trying to fetch the file. Is there a way to have the code hosted on jsDelivr too or any other CDN?

**Comment by stullesha** [comment]
I have had the timeout happen 2 or 3 times since I started using the package (since v 1.4.6). So, it is infrequent, but perhaps you can share both links in your readme file. I will keep an eye on this issue and also for other few people I know who are using this package.

**Comment by jahilldev** [comment]
@stullesha Sounds good, I'll add both links to the `README` for now. If you still have issues, please feedback and we can look into other options 👍

**Comment by stullesha** [comment]
Alright.
