### ISSUE TITLE
Not tracking downloads through form submit

### ISSUE THREAD

**Issue by androidacy-user** [jahilldev/minimal-analytics#34]
Hello!

We have a form, to enforce captcha and/or CSRF tokens on download. However, this library doesn't track those as downloads - even though they do result in a download, and the link the form submits to ends in a supported file ext.

Is this intended behavior, or a missing feature?

**Comment by jahilldev** [comment]
Hey @androidacy-user,

Automatically tracking downloads is tricky, especially if that download is triggered behind some server side logic that the client does not have access to. The official GA4 download tracking logic has similar limitations, unfortunately.

Currently automatic download tracking works primarily via `<a href="{fileUrl}" download />` tags. If a user clicks on an anchor, and the `href` contains a file url, this will trigger a download event.

My assumption here, in lue of more detail, is that your download is triggered via your server, and as such, the client has no access to this.

I think the easiest way forward would be to manually bind an onClick event to the `<submit />` button, which in turn triggers the `track()` function with the relevant "download" event arguments.

For example:

```js
track('G-XXXXXX', {
  type: 'file_download',
  event: {
    'ep.file_name': 'your_file_name.txt',
    'ep.file_extension': 'txt' // change accordingly
  }
})
```

I hope that helps!

**Comment by jahilldev** [comment]
@androidacy-user One other suggestion:

Although not _strictly_ valid, we could support the addition of the `download` attribute on HTML button attributes. This attribute can accept a file name, so checking for this would be trivial.

All you'd need to do is add the attribute to whatever button triggers your download, e.g:

```html
<form>
  <button download="your_file_name.txt" />
</form>
```

Given the attribute is only supported on anchor elements, this is entirely "correct", but would provide a standardised method to get around limitations like this without writing custom code.

Let me know! 👍

**Comment by jahilldev** [comment]
@androidacy-user Ok great, I'll see if I can get a PR up and published this week sometime 👍

**Comment by jahilldev** [comment]
@androidacy-user Here we are: https://github.com/jahilldev/minimal-analytics/pull/35

**Edit**
Published in [v1.8.7](https://github.com/jahilldev/minimal-analytics/releases/tag/ga4%4018.7)

**Comment by jahilldev** [comment]
@androidacy-user I'm going to close this issue for now, let me know how you get on, good or bad!

Thanks again for contributing 👍

**Comment by androidacy-user** [comment]
@jahilldev apologies for very delayed response but it works very well. One thing to note, the `download` attribute needs to be **just** the filename, not a full url. Otherwise, GA shows the `file_name` as being the full url.

**Comment by jahilldev** [comment]
Hey @androidacy-user,

Great, that's good news! 👍 

Yeh so I believe (from memory..) that I replicated what the official GA4 library sends in the `file_name` param, which should be the full path / url to the file. 

The reason being, (I assume), is that you might have similar named files on different origins, and this would allow differentiation between them in analytics. We're basically just taking the value of `href` or `download`, depending on use case, and sending that.

Thanks again for contributing!
