### ISSUE TITLE
Question about search results

### ISSUE THREAD

**Issue by bapps2** [jahilldev/minimal-analytics#40]
In my "Events" tab of GA4, I see a `view_search_results` field. Is that an event entry for those who used my search option/page on my site? BTW, wonderful project you have here.

**Comment by jahilldev** [comment]
Hey @bapps2, thanks for reaching out 👍 

Yes, so this event will show in your analytics if the current page has one of the following query params:

```js
['q', 's', 'search', 'query', 'keyword'];
```

See below for reference
https://github.com/jahilldev/minimal-analytics/blob/4b2f8e963c339ab05b5848f99e868e564a98fbea/packages/ga4/src/index.ts#L56

Let me know if that answers your question.

**Comment by bapps2** [comment]
No further questions. Cheers!
