### ISSUE TITLE
Change search results event

### ISSUE THREAD

**Issue by bwc69151** [jahilldev/minimal-analytics#46]
Is it possible to change `view_search_results` to `search_results`? https://prnt.sc/9Z1d6bOiGsau

**Comment by jahilldev** [comment]
Hi @bwc69151,

This parameter is currently set to the default defined by the official GA4 script. Modifying it in this package isn't currently supported.

That being said, the changes needed to support this via the config object shpuld be fairly straightforward.

Feel free to open a PR, all contributions welcome.

If I find some time I'll take a look myself 👍

**Comment by bwc69151** [comment]
> Feel free to open a PR, all contributions welcome.

I am not knowledgeable enough to do it. But it is not a priority for now. I just like one or two words in event names but this one is three.

**Comment by jahilldev** [comment]
OK, well I don't think this is something that's wanted widely enough to warrant a change right now.

However, if you do obtain the relevant knowledge to open a PR, feel free to do so 👍 

Closing for now.

Thanks again for reaching out.
