### ISSUE TITLE
How to use minimal analytics CDN-script with GA4? without node

### ISSUE THREAD

**Issue by kartashovio** [jahilldev/minimal-analytics#55]
I tried using https://minimalanalytics.com/ on my website. I placed the script in the head and replaced the identifier. It didn't work; I got an error in the console.

Then, I found out that the current version of the script is located here: https://cdn.jsdelivr.net/npm/@minimal-analytics/ga4/dist/index.js. However, I couldn't find how to adapt it for a regular website without Node.js. Where should I insert the Track ID?

Could you please tell me if this solution still works?

**Comment by kartashovio** [comment]
I found a way. Data collection works if you use this code:
```
<script src="https://cdn.jsdelivr.net/npm/@minimal-analytics/ga4/dist/index.js" async></script>
<script>
  window.minimalAnalytics = {
    trackingId: 'G-XXXXX', // <-- replace with your GA4 property ID
    autoTrack: true,
  };
</script>
```
But now I see an error in the console. Screenshot:
![image](https://github.com/user-attachments/assets/e767bb16-3ec8-4f18-9332-c23de1993311)
How can I fix this?

**Comment by jahilldev** [comment]
Hey @kartashovio,

The browser will throw this error when `localStorage` has hit the maximum allowed values. It's possible whichever browser you're using has hit this limit, and so attempting to set `clientId` is failing.

We really need a try / catch around uses of `localStorage` to prevent unhandled exceptions here.

The code that's causing this error is below:
https://github.com/jahilldev/minimal-analytics/blob/main/packages/shared/src/values.ts#L42-L53

If you clear your `localStorage` this should go away, but ideally we'd handle scenarios like this in the library and have some kind of fallback.

When I get some time I'll look into this, alternatively, feel free to have a bash yourself, PR's are welcome! :)

**Comment by kartashovio** [comment]
@jahilldev thanks a lot for the detailed answer. I'm not too good at technical stuff. Please tell me if I understand correctly that this is not a critical error? I can see that the data is being collected anyway.

**Comment by jahilldev** [comment]
Hey @kartashovio,

This will only be an issue with persistence for the client ID; In other words, if the storage fails for `clientId`, page reloads will re-generate new ID's as unique visitors. This could be an issue for tracking customer journeys across many page reloads.

I'd try clearing your browser storage, and then checking that the error has gone.

As mentioned, I think we need some kind of fallback here which I'll try and implement.

For now, you should be good to go though 👍

**Comment by kartashovio** [comment]
@jahilldev Thank you very much for your detailed response. I think I understand now that this is my personal problem, and not the problem of most visitors to my website. I cleared the cache, it helped. The multiplication of ClientID is a really important issue. I hope that no one else on the website will have this error.
