### ISSUE TITLE
Customize analytics endpoint

### ISSUE THREAD

**Issue by marshmallowcreme** [jahilldev/minimal-analytics#7]
I would like to reverse proxy calls to the GA server through my own domain using a Cloudflare worker in order to prevent ad blockers from blocking the request, so I would appreciate if you could add the ability to customize `analyticsEndpoint`. Thanks!

**Comment by jahilldev** [comment]
Hi @marshmallowcreme,

Thanks for reaching out, this is a great suggestion for an enhancement. 

I'll see if I can take a look later on this evening (GMT).

Will keep you posted 👍

**Comment by jahilldev** [comment]
@marshmallowcreme I've opened a PR here: https://github.com/jahilldev/minimal-analytics/pull/8

I should have it merged / published shortly.

You can now make use of an additional property, `analyticsEndpoint` to define your own collection path, e.g:

```js
window.minimalAnalytics = {
  /*[...]*/
  analyticsEndpoint: '/my/collection/path/or/proxy' // <-- can be anything
};
```

Thanks again for the suggestion! 👍

**Comment by marshmallowcreme** [comment]
@jahilldev: Just to clarify: The `analyticsEndpoint` string should include a domain name, correct? Not just a path. 

> You can now make use of an additional property, `analyticsEndpoint`, to define your own collection path, e.g:
> 
> ```js
> window.minimalAnalytics = {
>   /*[...]*/
>   analyticsEndpoint: '/my/collection/path/or/proxy' // <-- can be anything
> };
> ```

**Comment by jahilldev** [comment]
@marshmallowcreme Not necessarily, but you'll need to include one if your endpoint is hosted on a seperate domain to your website. 

Most likely, however, you'll be using some kind of edge function (Netlify or Vercel?), in which case you won't need to as this will be provisioned under your primary domain.

If you are using a separate domain, watch out for CORS related issues as the request is a POST.

Let me know if that makes sense.

**Comment by jahilldev** [comment]
@marshmallowcreme I'm going to close this issue for now, let me know if you need anything further.

Thanks again for contributing! 👍
